
version: "3.1"

services:
  flask-odoo-challenge:
    image: wudinaonao/flask-odoo-challenge:latest
    tty: true
    restart: always
    container_name: "flask-odoo-challenge"
    entrypoint: python /usr/app/App.py
    ports:
    - "8854:5000"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

# build command
# docker build --build-arg BUILD_DATE="$(date "+%F %T")"  --tag wudinaonao/flask-odoo-challenge:latest .
